# Generated by Django 4.1 on 2022-09-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
